GET http://localhost:2000/todos/?todo=Learn%20HTML

###
GET http://localhost:2000/todos/

###
POST http://localhost:2000/todos/
Content-Type: application/json

{
  "id": 4,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}

###
PUT http://localhost:2000/todos/2
Content-Type: application/json

{ "priority": "LOW" }

###
DELETE http://localhost:2000/todos/4